name: Enhanced Transmutation CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  enhanced-pathway-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy pandas seaborn
    
    - name: Run enhanced pathway validation
      run: |
        cd prototyping
        python test_enhanced_pathways.py
    
    - name: Run enhanced pathway demo
      run: |
        cd prototyping
        python quick_pathway_demo.py
      - name: Upload analysis results
      uses: actions/upload-artifact@v4
      with:
        name: enhanced-pathway-analysis
        path: prototyping/enhanced_comprehensive_analysis/

  cost-viability-analysis:
    runs-on: ubuntu-latest
    needs: enhanced-pathway-analysis
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy pandas
    
    - name: Analyze outsourcing cost structure
      run: |
        cd prototyping
        python outsourcing_cost_analyzer.py --budget=100 --target-roi=200
    
    - name: Generate monthly experiment plan
      run: |
        cd prototyping
        python monthly_experiment_planner.py > monthly_plan.txt
      - name: Upload monthly plan
      uses: actions/upload-artifact@v4
      with:
        name: monthly-experiment-plan
        path: prototyping/monthly_plan.txt

  comprehensive-integration:
    runs-on: ubuntu-latest
    needs: [enhanced-pathway-analysis, cost-viability-analysis]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy pandas seaborn
    
    - name: Run comprehensive integration test
      run: |
        cd prototyping
        python comprehensive_integration.py
      - name: Upload integration results
      uses: actions/upload-artifact@v4
      with:
        name: comprehensive-integration-results
        path: prototyping/comprehensive_pilot_assessment_*.json
